version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: "maven"
    directory: "/launch4j/maven"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "launch4j"
    commit-message:
      prefix: "build"
      include: "scope"
